### ISSUE TITLE
:apx :op1 :op2

### ISSUE THREAD

**Issue by pebbe** [rug-compling/noordergraf#17]
De tekst *geb. onder Oldekerk* wordt nu zo geannoteerd in penman:

```
:pob (c1 / location.n.01 
  :apx (c2 / village.n.02 :nam "OLDEKERK" :geo "53|13|10|N|6|20|20|E"))
```

Ik denk dat het beter zo kan:

```
:pob (c1 / village.n.02
  :nam "OLDEKERK"
  :geo "53|13|10|N|6|20|20|E"
  :apx "onder")
```

Dit maakt de definitie van `:pob` eenduidig, en vereenvoudigt het zoeken.

----

Update: nieuw voorstel
```
:pob (c1 / village.n.02
  :nam "OLDEKERK"
  :geo "53|13|10|N|6|20|20|E"
  :apx southOf
  :text "onder Oldekerk")
```

Andere mogelijke waardes voor `apx` zijn `northwestOf`, `near`...

**Comment by pebbe** [comment]
Vergelijkbaar is het gebruik van `:op1` en `:op2` bij `:age` en `:dur`.

Dit in penman:
```
:age (m1 / measure.n.02
         :op1-of (c3 / more.r.01
                     :op2 (m2 / measure.n.02
                              :qua 44
                              :mem (u1 / year.n.01))))
```

... zou beter zo kunnen:

```
:age (m1 / measure.n.02
         :qua 44
	 :unit year.n.01
	 :mod more.r.01)
```

Ik heb `:mem` verander in `:unit` omdat `:mem` voor twee verschillende doeleinden wordt gebruikt.

**Comment by jobos** [comment]
The class :Measure can have three relations:
:quantity (an integer or real number?),  :unit (the unit of measurement), and a comparison operator (<, =, >, ~, ≥ etc.)

**Comment by pebbe** [comment]
Zie https://github.com/rug-compling/noordergraf/issues/35
