### ISSUE TITLE
Hoe gaan de datastructuren eruit zien?

### ISSUE THREAD

**Issue by pebbe** [rug-compling/noordergraf#2]
Ik heb een eerste schets gemaakt op https://github.com/rug-compling/noordergraf/wiki/Datastructuur

Een paar van de dingen waar we over moeten beslissen:

 * welke predicaten gebruiken we
 * platte of geneste structuren
 * welke standaarden gebruiken we

Wat predicaten betreft: Ik denk niet dat het vol te houden is om aan predicaten van drie letters vast te houden. Hoe meer soorten info erbij komen, hoe moeilijker het wordt zonder goed leesbare predicaten.

Wat naamgeving betreft is het handig om verschillende predicaten voor elke context te gebruiken, dus bijvoorbeeld `name` voor een persoon, `placename` voor een geografische aanduiding, en `sitename` voor de naam van een begraafplaats.

**Comment by pebbe** [comment]
Wat standaarden betreft, ik las "ergens" dat foaf is vervangen door schema.org

Ik vind schema.org een beetje raar. Het lijkt vooral gericht op gebruik door commerciële webplatforms. Zo heeft [Place](https://schema.org/Place) attributen voor `hasDriveThroughService` en `branchCode`

**Comment by pebbe** [comment]
Waarom zijn alle strings in hoofdletters? Ik zou kleine letters gebruiken en, daar waar op een grafsteen namen of woorden met een hoofdletter beginnen, dat overnemen.

**Comment by pebbe** [comment]
Kunnen we [pluscodes](https://maps.google.com/pluscodes/) gebruiken als ID voor begraafplaatsen?
Of voor (historische) plaatsen die niet aanwezig zijn op geonames?

**Comment by jobos** [comment]
> Waarom zijn alle strings in hoofdletters? Ik zou kleine letters gebruiken en, daar waar op een grafsteen namen of woorden met een hoofdletter beginnen, dat overnemen.

Bij sommige fonts (small caps) is het niet duidelijk of er kleine of grote letters gebruikt worden. Mijn oplossing destijds was om alles te normaliseren naar hoofdletters. Maar dan verlies je inderdaad informatie.

**Comment by pebbe** [comment]
In penman worden predicaten gebruikt waarvan ik niet weet wat ze betekenen. Daarom weet ik ook niet of er iets speciaals moet gebeuren met de waarde die bij zo'n predicaat hoort. Bijvoorbeeld `:hco "19220"`. Is de waarde een string of een getal?

**Comment by pebbe** [comment]
In plaats van types als `t:person.n.01` kun je ook `t:person` gebruiken. Een type is immers een IRI die verwijst naar de definitie.

**Comment by pebbe** [comment]
Zie ook: https://github.com/rug-compling/noordergraf/wiki/Predicaten-gebruikt-voor-grafstenen
