### ISSUE TITLE
Gebruik van Getty Vocabularies voor grafsymbolen

### ISSUE THREAD

**Issue by pebbe** [rug-compling/noordergraf#29]
Zie [Getty Vocabularies](https://www.getty.edu/research/tools/vocabularies/) → [Art & Architecture Thesaurus](https://www.getty.edu/research/tools/vocabularies/aat/)

Hoe gebruiken we dit?

Voorbeeld: [anchor](http://vocab.getty.edu/aat/300219429) (op [t00136](https://noordergraf.rug.nl/tomb/t00136))

Simpel:
```turtle
@prefix aat: <http://vocab.getty.edu/aat/>

tomb:t00136 a :Tomb ;
  :sym aat:300219429 .
```

Bovenstaande is niet erg leesbaar.

Dit is beter:

```turtle
@prefix aat: <http://vocab.getty.edu/aat/>

tomb:t00136 a :Tomb ;
  :sym :Anchor .

:Anchor a rdfs:Class ;
  rdfs:subClassOf :Symbol ;
  rdfs:comment "anchor (watercraft equipment)"@eng ;
  rdfs:comment "anker (scheepsuitrusting)"@nld ;
  :aat aat:300219429 .
```

Andere vorm van definitie van `Anchor`:

```turtle
@prefix aat:   <http://vocab.getty.edu/aat/>
@prefix pwnid: <http://wordnet-rdf.princeton.edu/id/> .
@prefix wn20:  <http://www.w3.org/2006/03/wn/wn20/instances/> .

Anchor a rdfs:Class ;
  rdfs:subClassOf :Symbol ;
  rdfs:comment "Any of various devices dropped to the bottom of a body of water and designed to bury themselves there in order to restrict the movement of watercraft or other floating objects."@eng ;
  rdfs:comment "Scheepsanker"@nld ;
  owl:sameAs aat:300219429 , pwnid:02712226-n , wn20:synset-anchor-noun-1 .
```

Als je ook iets wilt met relaties tussen symbolen (en andere dingen), dan kun je zoiets doen:

```turtle
@prefix t00136: <https://noordergraf.rug.nl/tomb/t00136#> .

tomb:t00136 a :Tomb ;
  :sym t00136:sym1 .

t00136:sym1 a :Anchor .
```

**Comment by pebbe** [comment]
Een aparte prefix voor symbolen gebruiken?
Bijvoorbeeld om onderscheid te maken tussen `:Female` en `sym:Female`.

**Comment by pebbe** [comment]
Met getty heb je keus uit twee:

 * http://vocab.getty.edu/aat/300219429
 * http://vocab.getty.edu/page/aat/300219429
 
Welke te gebruiken? De sites linken naar elkaar. Op beide sites is ook een link naar andere formaten, bijvoorbeeld naar Turtle, en op beide sites is dat dezelfde link:

 * http://vocab.getty.edu/aat/300219429.ttl
 
Ik denk dat we dus de link zonder `page` moeten gebruiken.

**Comment by pebbe** [comment]
De gebruikte nummering in penman komt vaak niet overeen met de nummering in Wordnet 3.1

**Comment by pebbe** [comment]
[Hier](https://github.com/rug-compling/noordergraf/wiki/Symbolen) is een lijst van gebruikte grafsymbolen. Niet alle symbolen zijn terug te vinden in Getty Vocabularies. Meer symbolen (maar ook niet allemaal) zijn wel terug te vinden in Wordnet 3.1.

**Comment by pebbe** [comment]
Veel symbolen hebben als grafsymbool een speciale betekenis, en die vind je niet terug in Getty Vocabularies of Wordnet. Soms hebben twee figuren samen een betekenis als symbool, terwijl in Getty of Wordnet alleen de losse figuren voorkomen.

Op dodenakkers.nl zijn dit soort dingen wel omschreven. Dit zijn een paar van die figuren die ik gezien heb op onze foto's:

 * [Passer met winkelhaak](https://www.dodenakkers.nl/naslag/symboliek/201-passer-met-winkelhaak.html)
 * [Twee verbonden ringen](https://www.dodenakkers.nl/naslag/symboliek/204-ringen.html)
 * [Een afgebroken zuil](https://www.dodenakkers.nl/naslag/symboliek/210-zuil-afgebroken.html)

Ik denk dat we ook zoiets zouden moeten opzetten. Wordnet en zo schiet tekort.

**Comment by pebbe** [comment]
Voorbeeld van definitie voor grafsymbool gebruikt bij deze grafsteen: https://noordergraf.rug.nl/tomb/t00588

**Comment by pebbe** [comment]
Net zoals er webpagina's zijn met kaarten van begraafplaatsen, geboorteplaatsen en plaatsen van overlijden, zou er een webpagina met plaatjes van alle symbolen moeten komen.

**Comment by pebbe** [comment]
Het is sowieso beter om symbolen niet direct onder Tomb te zetten, maar via een tussenniveau, omdat je dan extra info kunt toevoegen, specifiek over het symbool zoals het op deze grafsteen staat.

```turtle
tomb:t00136 a :Tomb ;
  :symbol [
    a :Symbol ;
    :symbolType :Anchor ;
    :comment "..."
  ] .
```

**Comment by pebbe** [comment]
```turtle
tomb:t00136 a :Tomb ;
  :symbol [
    a symbol:Anchor  ;
    :comment "..."
  ] .
```

**Comment by jobos** [comment]
weeping willow: https://thenounproject.com/icon/willow-607312/
frond: https://thenounproject.com/icon/yew-frond-463028/

**Comment by pebbe** [comment]
Alle genoemde symbolen:

https://noordergraf.rug.nl:10036/#/repositories/noordergraf/query/d/SELECT%20DISTINCT%20?b%20%7B%0A%20%20?a%20:symbol%20/%20a%20?b%20.%0A%7D%20ORDER%20BY%20?b

**Comment by jobos** [comment]
Is het niet handiger om symbolic links van www/sym/src naar sym te maken, zoals ik nu even voor Frond.png heb gedaan?
Dan heb je meteen ook een verbinding tussen de originele bestandsnaam en de naam zoals wij die gebruiken.

**Comment by pebbe** [comment]
Enkele kandidaten:

https://www.shutterstock.com/nl/collections/309729463-c7035f95

**Comment by jobos** [comment]
Op https://noordergraf.rug.nl/symbol/ zijn niet alle symbolen zichtbaar. Misschien staan de leesrechten niet goed?

**Comment by jobos** [comment]
Kijk eens hier: https://thenounproject.com/search/icons/?iconspage=1&q=wreath

**Comment by jobos** [comment]
de ploeg op t01041 is geen ploeg maar zo'n omgekeerde fakkel
aangezien er geen andere ploegen zijn vervalt de ploeg!

**Comment by pebbe** [comment]
Voorstellen voor aanpassingen:

`Naam_naam` → `NaamNaam`

BrokenFrond
-  [t00021](https://noordergraf.rug.nl/img/t00021.jpg) is geen (samengesteld) blad maar een tak
-  BrokenTwig ?

Blazon
-  CoatOfArms, Escutcheon
-  Wapenschild

BrokenFlower -> andere afbeelding, geen gebroken maar een geknakte bloem
-  geknakte bloem
-  is er geen betere Engelse benaming?

Curtain
-  betere benaming, een term uit de heraldiek?
-  betere afbeelding?

Galleon
-  Full-rigged ship, Square-rigged vessel
-  Volschip, Dwarsgetuigd schip

Sailboat
-  Long rigged ship (?)
-  Langsgetuigd schip
-  Sommige afbeeldingen zijn van platbodems, dat noem je geen zeilboot

Sandglass
-  Hourglass

Schaalvandeleviet
-  Op afbeeldingen die ik kan vinden ziet dat er anders uit. Een kom met een schenkkan.
-  Is [t00735](https://noordergraf.rug.nl/img/t00735.jpg) soms een olielamp?

Treble_clef
- GClef
- https://en.wikipedia.org/wiki/Clef#G-clefs
