### ISSUE TITLE
:ent (:entry) vervangen door :person ?

### ISSUE THREAD

**Issue by pebbe** [rug-compling/noordergraf#33]
Kunnen we groepen weglaten, en alleen met individuen werken? Dan zou je `:ent` kunnen hernoemen naar `:person`.

Voorbeelden:

Dit ...
```turtle
@prefix t00972: <https://noordergraf.rug.nl/tomb/t00972#> .

t00972:p1
  a :Male ;
  :nam "AREND AASMAN" .

t00972:p2
  a :Female ;
  :nam "CATRIENA VOS" .

t00972:p3
  a :Male ;
  :nam "AREND AASMAN" ;
  :rol [
    a :Son.n.01 ;
    :tgt t00972:g1
  ] .

t00972:g1
  a :Group.n.01 ;
  :mem t00972:p1, t00972:p2 .
```

... kan ook zo ...

```turtle
@prefix t00972: <https://noordergraf.rug.nl/tomb/t00972#> .

t00972:p1
  a :Male ;
  :nam "AREND AASMAN" .

t00972:p2
  a :Female ;
  :nam "CATRIENA VOS" .

t00972:p3
  a :Male ;
  :nam "AREND AASMAN" ;
  :rol [
    a :Son.n.01 ;
    :tgt t00972:p1
    :tgt t00972:p2
  ] .
```

En dit ...

```turtle
@prefix t00000: <https://noordergraf.rug.nl/tomb/t00000#> .

t00000:p1
  a :Male ;
  :nam "JAN WERKMAN" ;
  :rol [
    a :Husband.n.01 ;
    :att "LIEVE" ;
    :tgt t00000:g1
  ], [
    a :Father.n.01 ;
    :tgt t00000:g1
  ] .

t00000:g1
  a :Group.n.01 ;
  :rol [
    a :Commemorator.n.01 ;
    :tgt t00000:p1
  ] .
```

... zou ook zo kunnen ...

```turtle
@prefix t00000: <https://noordergraf.rug.nl/tomb/t00000#> .

t00000:p1
  a :Male ;
  :nam "JAN WERKMAN" ;
  :rol [
    a :Husband.n.01 ;
    :att "LIEVE"
  ], [
    a :Father.n.01
  ] .
```

**Comment by jobos** [comment]
Het gebruiken van groepen maakt alles gecompliceerder. Dus als ze altijd geelimineerd kunnen worden dan is dit een goede oplossing,

**Comment by pebbe** [comment]
Huidig plan:

 * `:ent` → `:subject` voor personen die begraven liggen in het betreffende graf, of waaraan een gedenksteen is gewijd
 * `:ent` → `:creator` voor maker van de steen
 * overigen verwijderen

Huidige situatie:

 * `:creator` zou in orde moeten zijn.
 * `:subject` wordt nu nog gebruikt voor elke `:Person`, `:Male` en `:Female`. Die moeten dus allemaal gecontrolleerd worden, en zonodig moet de relatie worden verwijderd.
 * Overal waar nog `:ent` gebruikt wordt moet aangepast worden.
