### ISSUE TITLE
De Wilp, Friesland

### ISSUE THREAD

**Issue by pebbe** [rug-compling/noordergraf#36]
https://noordergraf.rug.nl/tomb/t01067

Geboren in De Wilp, Friesland. Maar ik kan geen plaats De Wilp in Friesland vinden.

**Comment by jobos** [comment]
Vroeger was er ook een De Wilp in Friesland. Het dorpje lag zowel in Groningen als in Friesland. Nu heet het Friese gedeelte Siegerswoude. Zie: https://nl.wikipedia.org/wiki/Siegerswoude_(Opsterland)
