### ISSUE TITLE
Tussenniveaus voor data van grafstenen

### ISSUE THREAD

**Issue by pebbe** [rug-compling/noordergraf#40]
Eigenschappen worden vaak in twee stappen gegeven.

Voorbeelden:

```turtle
:placeOfDeath [
    a :City.n.01 ;
    :name "LJOUWERT"@fry ;
    :place place:Leeuwarden2751792
  ]

:age [
    a :Age ;
    :duration "P44Y"^^xsd:duration ;
    :text "ruim 44 Jaren"
  ] ;
```

Dit is niet consistent gedaan.  Bij geboortedatum is er geen tussenniveau:

```turtle
:dateOfBirth "1784-03-28"^^xsd:date ;
```

Zouden we nog eens goed moeten kijken waar we wel een tussenniveau gebruiken, en waar niet?

Zou je ze overal kunnen weglaten? Dan krijg je dit:

```turtle
:placeOfDeath place:Leeuwarden2751792 ;

:age "P44Y"^^xsd:duration ;
```

Hiermee vervalt de mogelijkheid specifieke info over dit ene item op deze ene grafsteen op te nemen in de eigenschap. De vraag is, wat wil je behouden?

Als je de tussenniveaus weg wilt halen, maar toch die extra info wilt weergeven, dan kun je zoiets doen:

```turtle
:placeOfDeath place:Leeuwarden2751792 ;
:placeOfDeathText "LJOUWERT"@fry ;

:age "P44Y"^^xsd:duration ;
:ageText "ruim 44 Jaren" ;
```

Maar dat is niet fraai, en is niet toepasbaar wanneer een eigenschap meer dan eens voorkomt.

Aan alle grafstenen moeten sowieso de complete transcripties worden toegevoegd. Dan is alle informatie er, alleen niet per se tot in detail gecodeerd. Wil je een complete semantische analyse van alle tekst?

**Comment by pebbe** [comment]
Op zich zijn die tussenniveaus geen probleem. Je moet alleen goed nadenken bij welke eigenschappen je ze gebruikt, en bij welke niet.

**Comment by jobos** [comment]
Ja dat moet dus goed in de annotatiehandleiding beschreven worden!
