### ISSUE TITLE
Namen van personen, plaatsen, bedrijven, etc.

### ISSUE THREAD

**Issue by pebbe** [rug-compling/noordergraf#51]
We kunnen niet overal waar het om een of andere naam gaat de relatie `:name` gebruiken, omdat het om verschillende datatypes gaat. De naam van een bedrijf is een string, maar de naam van een persoon is een `Name`-object.

Er is ook een probleem met geboorteplaats en plaats van overlijden. Je hebt `Person` → `placeOfDeath` → `Place`, maar ook `Place` → `placename` → "Leeuwarden". Twee verschillende soorten objecten, beiden een `Place`.

```turtle

t00019:p1
  a :Female ;
  :name [
    a :Name ;
    :fullname "Hilje Hofman" ;
    :text "hilje hofman", "hilly"
  ] .

t00498:p1
  a :Male ;
  :placeOfDeath [
    a :Place ;
    :text "LJOUWERT"@fry ;
    :place place:Leeuwarden2751792
  ] .

place:Leeuwarden2751792
  a :Place ;
  :placename "Leeuwarden" .

tomb:t00498
  a :Tomb ;
  :site site:fr8917AVleeuwarden .

site:fr8917AVleeuwarden
  a :Site ;
  :sitename "Joodse Begraafplaats, Leeuwarden" ;
  :address [
    a schema:PostalAddress ;
    schema:streetAddress "Spanjaardslaan 76" ;
    schema:addressLocality "Leeuwarden" ;
    schema:addressRegion "Friesland" ;
    schema:addressCountry "NL" ;
    schema:postalCode "8917 AV"
  ] .

t00021:o
  a :Company ;
  :nam "Nederlandse Spoorwegen" .
```

**Comment by jobos** [comment]
t00019:p1
  a :Female ;
  :personname [
    a :Name ;
    :text "Hilje Hofman" ;
    :text "hilje hofman", "hilly"
  ] .

**Comment by jobos** [comment]
Beter:


t00019:p1
a :Female ;
:name [
  a :Name ;
:fullname "Hilje Hofman" ;
:maidename "...."
:prefix "...."
:text "hilje hofman", "hilly"
] .
