### ISSUE TITLE
Graven zonder foto

### ISSUE THREAD

**Issue by pebbe** [rug-compling/noordergraf#53]
Zie [hier](https://noordergraf.rug.nl:10036/#/repositories/noordergraf/query/d/SELECT%20?g%20%7B%0A%20%20GRAPH%20?g%20%7B%0A%20%20%20%20?t%20a%20:Tomb%20.%0A%20%20%20%20FILTER%20NOT%20EXISTS%20%7B%20?t%20:image%20?i%20%7D%0A%20%20%7D%0A%7D%20ORDER%20BY%20?g).

**Comment by jobos** [comment]
Klopt, die foto ervan ontbreekt en kan ik ook niet meer vinden.
Deze kan dus in de prullenbak.

**Comment by jobos** [comment]
00658

**Comment by jobos** [comment]
foto toegevoegd
