### ISSUE TITLE
wel of geen subject

### ISSUE THREAD

**Issue by pebbe** [rug-compling/noordergraf#59]
In alle data over grafstenen die al is ingevoerd moet gecontrolleerd worden welke op de steen genoemde personen *subject* zijn.

**Comment by pebbe** [comment]
Wat is de betekenis van *subject*?

Voor graven is het degene(n) die hier begraven zijn.

Hoe zit het met gedenkstenen? Degene(n) aan wie dit monument is gewijd?

Dan heeft *subject* twee verschillende betekenissen. Dat lijkt mij niet goed.

**Comment by jobos** [comment]
Het is alleen de tweede betekenis, aan wie de steen/item/monument gewijd is
