### ISSUE TITLE
Welke taalcodes gebruiken we? En waar gebruiken we ze?

### ISSUE THREAD

**Issue by pebbe** [rug-compling/noordergraf#6]
In de definitie van Turtle, onder [2.5.1 Quoted Literals](https://www.w3.org/TR/turtle/#turtle-literals) staan voorbeelden van het gebruik van language tags uit ISO 639-1, codes van twee letters. Volg je de links dan ga je van RDF 1.1 Concepts and Abstract Syntax, [3.3 Literals](https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal) naar  BCP47, naar RFC 5646, waar bij de [voorbeelden](https://www.rfc-editor.org/rfc/rfc5646.html#appendix-A) ook een code van drie letters wordt gebruikt. 

Nergens staat vermeld welke standaard hier gebruikt wordt.

Op [Wikipedia](https://en.wikipedia.org/wiki/ISO_639-2#History_and_relationship_to_other_ISO_639_standards) staat:

> In practice, ISO 639-2 has largely been superseded by ISO 639-3 (2007), which includes codes for all the individual languages in ISO 639-2 plus many more. It also includes the special and reserved codes, and is designed not to conflict with ISO 639-2. ISO 639-3, however, does not include any of the collective languages in ISO 639-2; most of these are included in ISO 639-5.

Als een externe crawler onze data bekijkt, dan moet die toch weten welke ISO-variant we gebruiken om de taalcodes goed te interpreteren?

Het lijkt er op dat we het best [ISO 639-3](https://iso639-3.sil.org/) kunnen gebruiken. In de oude data (in penman-formaat) kom ik onderstaande taalcodes in hoofdletters tegen. Ik heb de definitie er bij gezocht volgens ISO 639-3. Kloppen deze?

 * FRY: [Fries](https://iso639-3.sil.org/code/fry)
 * ENG: [Engels](https://iso639-3.sil.org/code/eng)
 * FRA: [Frans](https://iso639-3.sil.org/code/fra)
 * HEB: [Hebreeuws](https://iso639-3.sil.org/code/heb)
 * MSA: [Maleis (macrolanguage)](https://iso639-3.sil.org/code/msa)
 * NDS: [Nedersaksisch](https://iso639-3.sil.org/code/nds)
 * NLD: [Nederlands](https://iso639-3.sil.org/code/nld)

Er is trouwens ook Gronings: [gos](https://iso639-3.sil.org/code/gos)

**Comment by jobos** [comment]
Lijkt me goed!

**Comment by pebbe** [comment]
We zouden speciekere taalcodes kunnen gebruiken. In de huidige data komen drie items met NDS voor. 
t00594 is Gronings.
t00929 is Drents.
Van t00511 is het niet duidelijk, maar het is op een begraafplaats in Groningen, dus zou je op Gronings kunnen gokken.

Voor Gronings kun je [gos](https://iso639-3.sil.org/code/gos) gebruiken.
Voor Drents kun je [drt](https://iso639-3.sil.org/code/drt) gebruiken.

**Comment by pebbe** [comment]
Er zijn nog steeds plaatsen waar `:lan` wordt gebruikt, (altijd?) als globale taalaanduiding van een graf. Dit moet weg. 

Alleen teksten moeten een taalaanduiding krijgen, en dan als taaltag aan de string. Welke teksten? Citaten wel, persoonsnamen niet (tenzij vertalingen van namen, zoals *Karel de Grote*). En de rest?

**Comment by pebbe** [comment]
Je zou `@nld` kunnen weglaten, en op plaatsen waar het geen Nederlands is, maar je weet niet welke taal het wel is kun je `@und` gebruiken. Zie [wikipedia: Special codes](https://en.wikipedia.org/wiki/ISO_639-3#Special_codes)

**Comment by jobos** [comment]
alle strings kunnen een taaltag krijgen, dus namen, citaten etc.
