### ISSUE TITLE
Relaties tussen personen (Turtle* en SPARQL* / TriG / rdf:value)

### ISSUE THREAD

**Issue by pebbe** [rug-compling/noordergraf#8]
Relaties met eigenschappen worden nu opgesplitst, zodat we iets over het predicaat kunnen zeggen:

```
p1 :rol r1 .
r1 a t:mother.n.01 .
r1 :tgt p2 .
r1 :att "lieve" .
```

Hierin is mother eigenlijk een predicaat, dus dit zou beter zijn:

```
p1 :mother p2 .
```

Wat doe je dan met "lieve"?

In Turtle* en SPARQL* kun je attributen aan een relatie geven.

```
<< p1 :mother p2 >> :att "lieve" .
```

Deze syntax valt onder [RFD-star](https://w3c.github.io/rdf-star/). Het is (nog) geen W3C-standaard, maar wordt al wel op diverse platforms ondersteund. Ook AllegroGraph ondersteunt dit.

Gaan we dit gebruiken, of houden we het bij standaard Turtle?

**Comment by jobos** [comment]
Rollen kunnen naast attributen ook nog aan andere dingen gekoppeld worden. Dus ik zou niet voor de tweede optie gaan (RDF-star).  Bijvoorbeeld:

(t00069 / tombstone.n.01
        :ent (p1 / female.n.02
                 :nam "AUKE KORNELIA VEENHUIS"
	         :dob "12-11-1867"
                 :dod "08-07-1943"
                 :rol (r1 / wife.n.01 :tgt p2 :att "LIEVE")
                 :rol (r2 / mother.n.01)
                 :rol (r3 / widow.n.01 :tgt p3 :bef r1))
	:ent (p2 / male.n.02
                 :nam "T. DE BOER")
        :ent (p3 / male.n.02
                 :nam "J. KNAPPER"))

**Comment by pebbe** [comment]
Ik zie het probleem. Met `:bef` verwijs je naar een tripple.

Er is een andere oplossing, het gebruik van named graphs. Daarvoor zijn twee invoerformaten, N-Quads en TriG. TriG is het simpelste, een kleine uitbreiding op het Turtle-formaat. Bovenstaand voorbeeld in penman zou dit kunnen worden in TriG:

```
@prefix :     <https://noordergraf.rug.nl/pred/> .
@prefix g:    <https://noordergraf.rug.nl/graph#> .
@prefix t:    <https://noordergraf.rug.nl/type/> .
@prefix item: <https://noordergraf.rug.nl/item/> .

item:t00069 a t:tombstone.n.01 ;
  :ent item:t00069.p1 ,
       item:t00069.p2 ,
       item:t00069.p3 .

item:t00069.p1 a t:female.n.02 ,
      t:person.n.01 ;
  :dob "1867-11-12" ;
  :dod "1943-07-08" ;
  :nam "AUKE KORNELIA VEENHUIS" .

g:t00069.r1 {
  item:t00069.p1 :wife.n.01 item:t00069.p2 .
}

g:t00069.r2 {
  item:t00069.p1 :mother.n.01 _:t00069.r2 .
}

g:t00069.r3 {
  item:t00069.p1 :widow.n.01 item:t00069.p3 .
}

g:t00069.r1 :att "LIEVE" .

g:t00069.r3 :bef g:t00069.r1 .

item:t00069.p2 a t:male.n.02 ,
      t:person.n.01 ;
  :nam "T. DE BOER" .

item:t00069.p3 a t:male.n.02 ,
      t:person.n.01 ;
  :nam "J. KNAPPER" .
```

En in SPARQL kun je zoeken met named graphs. Hieronder zoek je een relatie voor (`:bef`) een andere relatie:

```
PREFIX : <https://noordergraf.rug.nl/pred/>
SELECT ?p ?rol1 ?p1 ?rol2 ?p2 ?x ?y {
  ?x :bef ?y .
  GRAPH ?x { ?p ?rol1 ?p1 . }
  GRAPH ?y { ?p ?rol2 ?p2 . }
}
```

**Comment by pebbe** [comment]
Met het gebruik van een named graph alleen wanneer je het nodig hebt voorkom je dat je verschillende niveau's van nesting door elkaar moet gebruiken. Je gebruikt een platte structuur voor iets wat heel vaak voorkomt, tot je een zeldzaam apart geval tegenkomt dat niet in die platte structuur past. Als je er dan een named graph van maakt kun je dezelfde platte structuur blijven gebruiken.

**Comment by pebbe** [comment]
De idiomatische manier (volgens w3.org) om attributen aan relaties te geven gedemonstreerd met een voorbeeld.

```turtle
@prefix :     <https://noordergraf.rug.nl/pred/> .
@prefix t:    <https://noordergraf.rug.nl/type/> .
@prefix tomb: <https://noordergraf.rug.nl/tomb/> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

# een simpele relatie
tomb:t01.p1 a t:male ;
  :husband tomb:t01.p2 .

# een relatie met een attribuut
tomb:t02.p1 a t:male ;
  :husband [ rdf:value tomb:t02.p2 ;
             :since "1899"
           ] .

# een relatie zonder object
tomb:t03.p1 a t:male ;
  :husband [ ] .
```

Enkele query's op bovenstaande data

Iedere husband met object:

```sparql
SELECT ?a ?b {
  ?a :husband ?b .
}
ORDER BY ?a
```

| a | b |
|----|----|
| t01.p1 | t01.p2 |
| t02.p1 | _:b9359C5D6x10 |
| t03.p1 | _:b9359C5D6x11 |

Iedere husband met object in relatie met attributen:

```sparql
SELECT ?a ?b {
  ?a :husband / rdf:value ?b .
}
ORDER BY ?a
```
| a | b |
|----|----|
| t02.p1 | t02.p2 |

Iedere husband met elk object, optioneel in relatie met attributen, Dit geeft `t01.p1` twee keer:

```sparql
SELECT ?a ?b {
  ?a :husband / rdf:value? ?b .
}
ORDER BY ?a
```

| a | b |
|----|----|
| t01.p1 | t01.p2 |
| t02.p1 | t02.p2 |
| t02.p1 | _:b9359C5D6x10 |
| t03.p1 | _:b9359C5D6x11 |

Iedere husband met vrouw:


```sparql
SELECT ?a ?b {
  ?a :husband / rdf:value? ?b .
  ?b a t:female .
}
ORDER BY ?a
```

| a | b |
|----|----|
| t01.p1 | t01.p2 |
| t02.p1 | t02.p2 |

Iedere husband met vrouw of man:

```sparql
SELECT ?a ?b {
  ?a :husband / rdf:value? ?b .
  { { ?b a t:female . } UNION { ?b a t:male . } }
}
ORDER BY ?a
```

| a | b |
|----|----|
| t01.p1 | t01.p2 |
| t02.p1 | t02.p2 |


Dit is correct in Sparql 1.1, maar wordt niet ondersteund in AllegroGraph:

```sparql
SELECT ?a ?b {
  ?a :husband / rdf:value? ?b .
  ?b a t:female|t:male . 
}
ORDER BY ?a
```

**Comment by pebbe** [comment]
Dit gaan we niet doen
